# Generated by Django 3.2.5 on 2025-03-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='docs/')),
                ('dataType', models.CharField(default='unstructured', max_length=15)),
                ('documentContent', models.TextField()),
            ],
        ),
    ]
